version: '3.6'

services:
  auth:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_URI=mongodb://mongo_username:mongo_password@mongodb

  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo_username
      - MONGO_INITDB_ROOT_PASSWORD=mongo_password
    ports:
      - "27017:27017"
    volumes:
      - "mongo:/data/db"

volumes:
  mongo:
